version: "3.9"
services:
  api:
    env_file:
      - .env
    build:
      context: ./api
      args:
        - DEV=false
    volumes:
      - ./api/app:/app
      - /var/log/live_streaming_list:/var/log/live_streaming_list  # 로그 파일을 저장할 디렉토리 마운트
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - WERKZEUG_DEBUG_PIN=off
      - TZ="Asia/Seoul"
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 config.wsgi:application --workers 4 --timeout 120 --log-level debug
             --access-logfile '/var/log/live_streaming_list/access.log' --error-logfile '/var/log/live_streaming_list/error.log'"
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - app-network

  celery:
    build:
      context: ./api
    command: celery -A config worker --loglevel=info
    volumes:
      - ./api/app:/app
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
