version: "3.9"
services:
  api:
    env_file:
      - .env
    build:
      context: ./api
      args:
        - DEV=true
    volumes:
      - ./api/app:/app
      - ./pyproject.toml:/app/pyproject.toml
      - ./mypy.ini:/app/mypy.ini
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - WERKZEUG_DEBUG_PIN=off
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver_plus 0.0.0.0:8000"
