version: "3.11"
services:
  api:
    build: ./api
    volumes:
      - ./api/app:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 config.wsgi:application --workers 4 --log-level debug"
