version: "3.11"
services:
  api:
    env_file:
      - .env
    build:
      context: ./api
      args:
        - DEV=false
    volumes:
      - ./api/app:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - WERKZEUG_DEBUG_PIN=off
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 config.wsgi:application --workers 4 --timeout 120 --log-level debug"
