# Generated by Django 5.0.6 on 2024-06-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeStreamDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('streaming_link', models.URLField(max_length=1024)),
                ('channel_descript', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
