# Generated by Django 5.0.6 on 2024-06-17 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("youtube", "0003_remove_youtubemodel_details_youtubestreamdetails"),
    ]

    operations = [
        migrations.DeleteModel(
            name="YoutubeStreamDetails",
        ),
    ]
