# Generated by Django 5.0.6 on 2024-06-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveStreamingCategories",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("categories", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "라이브 스트리밍 Category",
                "verbose_name_plural": "라이브 스트리밍 Category 목록",
                "db_table": "live_streaming_genre_table",
            },
        ),
    ]
