# Generated by Django 5.0.6 on 2024-06-28 10:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_livestreamingcategories"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commonmodel",
            old_name="followers",
            new_name="channel_followers",
        ),
        migrations.AddField(
            model_name="commonmodel",
            name="channel_profile_image",
            field=models.URLField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="livestreamingcategories",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="livestreamingcategories",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="commonmodel",
            name="platform",
            field=models.CharField(
                choices=[("youtube", "YouTube"), ("chzzk", "Chzzk"), ("afreecatv", "AfreecaTV"), ("twitch", "Twitch")],
                default="youtube",
                max_length=50,
            ),
        ),
    ]
