# Generated by Django 5.0.6 on 2024-07-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_rename_followers_commonmodel_channel_followers_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commonmodel",
            options={},
        ),
        migrations.AlterField(
            model_name="commonmodel",
            name="concurrent_viewers",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
