# Generated by Django 5.0.6 on 2024-06-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_googleuserid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="oauth_platform",
            field=models.CharField(
                choices=[("none", "None"), ("google", "Google"), ("naver", "Naver")],
                default="",
                max_length=50,
                null=True,
            ),
        ),
    ]
