# Generated by Django 5.0.6 on 2024-06-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_oauth_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="oauth_platform",
            field=models.CharField(
                choices=[("none", "None"), ("google", "Google"), ("naver", "Naver")],
                default="none",
                max_length=50,
                null=True,
            ),
        ),
    ]
