# Generated by Django 5.0.6 on 2024-06-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_oauth_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
