# Generated by Django 5.0.6 on 2024-07-02 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_user_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="naveruserid",
            name="user",
        ),
        migrations.RemoveField(
            model_name="user",
            name="oauth_platform",
        ),
        migrations.CreateModel(
            name="UserOAuth2Platform",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "oauth_platform",
                    models.CharField(
                        choices=[("none", "None"), ("google", "Google"), ("naver", "Naver")],
                        default="none",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("oauth2_user_id", models.CharField(max_length=255, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="GoogleUserId",
        ),
        migrations.DeleteModel(
            name="NaverUserId",
        ),
    ]
