# Generated by Django 5.0.6 on 2024-06-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChzzkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255)),
                ('thumbnail', models.URLField(max_length=1024)),
                ('live_viewer', models.PositiveIntegerField()),
                ('urls', models.URLField(max_length=1024)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'chzzk',
            },
        ),
    ]
