# Generated by Django 5.0.6 on 2024-06-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chzzk", "0002_remove_chzzkmodel_live_viewer_remove_chzzkmodel_urls_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chzzkmodel",
            name="platform",
            field=models.CharField(
                choices=[
                    ("youtube", "YouTube"),
                    ("chzzk", "Chzzk"),
                    ("afreecatv", "AfreecaTV"),
                ],
                default="chzzk",
                max_length=50,
            ),
        ),
    ]
