# Generated by Django 5.0.6 on 2024-06-17 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("youtube", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="youtubemodel",
            name="live_viewer",
        ),
        migrations.RemoveField(
            model_name="youtubemodel",
            name="urls",
        ),
        migrations.AddField(
            model_name="youtubemodel",
            name="concurrent_viewers",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="youtubemodel",
            name="details",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="youtube_stream",
                to="common.youtubestreamdetails",
            ),
        ),
        migrations.AddField(
            model_name="youtubemodel",
            name="platform",
            field=models.CharField(
                choices=[("youtube", "YouTube"), ("chzzk", "Chzzk"), ("afreecatv", "AfreecaTV")],
                default="youtube",
                max_length=50,
            ),
        ),
    ]
