# Generated by Django 5.0.6 on 2024-06-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0003_remove_youtubemodel_details_youtubestreamdetails"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="youtubestreamdetails",
            name="youtube_model",
        ),
        migrations.DeleteModel(
            name="YoutubeModel",
        ),
        migrations.DeleteModel(
            name="YoutubeStreamDetails",
        ),
    ]
