# Generated by Django 5.0.6 on 2024-06-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afreecatv", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="afreecatvmodel",
            name="live_viewer",
        ),
        migrations.RemoveField(
            model_name="afreecatvmodel",
            name="urls",
        ),
        migrations.AddField(
            model_name="afreecatvmodel",
            name="concurrent_viewers",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
