# Generated by Django 5.0.6 on 2024-06-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afreecatv", "0002_remove_afreecatvmodel_live_viewer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="afreecatvmodel",
            name="platform",
            field=models.CharField(
                choices=[
                    ("youtube", "YouTube"),
                    ("chzzk", "Chzzk"),
                    ("afreecatv", "AfreecaTV"),
                ],
                default="afreecatv",
                max_length=50,
            ),
        ),
    ]
