# Generated by Django 5.0.6 on 2024-06-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("afreecatv", "0003_afreecatvmodel_platform"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AfreecaTvModel",
        ),
    ]
