name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: docker-compose up -d

    - name: Run Black
      run: docker-compose run --rm api sh -c 'black . --check'

    - name: Run Isort
      run: docker-compose run --rm api sh -c 'isort . --check-only'

    - name: Run Mypy
      run: docker-compose run --rm api sh -c 'mypy --config-file /app/mypy.ini .'
