name: Deploy to EC2

on:
  push:
    branches:
      - backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.REMOTE_EC2_PRIVATE_KEY }}

    - name: Copy files via rsync
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.REMOTE_EC2_USER }}@${{ secrets.REMOTE_EC2_IP }}:~/temp

    - name: Execute remote commands
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_EC2_USER }}@${{ secrets.REMOTE_EC2_IP }} << 'EOF'
          cd ~/live_streaming_lists
          docker-compose -f docker-compose-deploy.yml down
          cd ~
          mkdir -p old_version
          cp -r live_streaming_lists/ old_version/
          rm -rf live_streaming_lists
          git clone -b backend git@github.com:Scanf-s/live_streaming_lists.git
          cp ~/.env/.env ~/live_streaming_lists/
          cd ~/live_streaming_lists
          docker-compose -f docker-compose-deploy.yml up --build -d
        EOF
